### ISSUE TITLE
Demo for main-net feature "ready"

### ISSUE THREAD

**Issue by mudler** [masa-finance/roadmap#52]
As we are preparing to launch bittensor release for mainnet deployment on 24th of July, we want to have a demo of showing the basic functionalities and kick-off on how things are configured.

Depends on:

- https://github.com/masa-finance/roadmap/issues/20
- https://github.com/masa-finance/masa-bittensor/issues/122
- https://github.com/masa-finance/masa-bittensor/issues/124
- https://github.com/masa-finance/masa-bittensor/issues/123

## Acceptance criteria

We want to see in the demo at least:
- the award system
- mainnet hyprparameters and setting
- infrastructure considerations

**Comment by grantdfoster** [comment]
Demo'd the current state of the codebase, showing validators, miners, scoring, and versioning.  Outcomes captured here in [this miro board](https://miro.com/app/board/uXjVKqeFzWA=/) and will be converted into further tickets after additional review / conversations are had
