### ISSUE TITLE
spike: community outreach

### ISSUE THREAD

**Issue by mudler** [masa-finance/roadmap#74]
As we plan to go main net soon, there are several collateral items that we want to address as part of this, for instance:

- [ ] Validator engagement
- [ ] External stakeholders engagement
- [ ] Influencers outreach
- [ ] MASA validators
- [ ] Official Discord channel in subnet

we don't know yet all the activities that have to be done prior to the release, and hence this ticket is to track and organize the collateral activities and to spike around what have to be done.

## Acceptance criteria

- [ ] We know what are the activities to carry over before main net release
- [ ] We have all the follow-up items open and tracked in the roadmap (ping @mudler @teslashibe )

**Comment by Luka-Loncar** [comment]
@teslashibe will update us on outcomes form this spike. Some of these are p0 so they are pretty important.
